USE [NgyMengDB]
GO

/****** Object:  Table [dbo].[ITEM_RECIEVE_MASTER]    Script Date: 08/04/2018 12:37:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ITEM_RECIEVE_MASTER](
	[RECEIVE_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[RECEIVE_DATE] [date] NULL,
	[REFERAN_INVOICE_NO] [nvarchar](50) NULL,
	[REFERAN_INVOICE_DATE] [date] NULL,
	[REFERAN_DUE_DATE] [date] NULL,
	[REFERAN_TEAM] [nvarchar](50) NULL,
	[SUPPLY_NO] [nvarchar](50) NULL,
	[SUPPLY_NAME] [nvarchar](50) NULL,
	[SUPPLY_INFO] [nvarchar](50) NULL,
	[TOTAL_AMOUNT_EXCLUDE_VAT] [numeric](18, 3) NULL,
	[VAT] [numeric](18, 3) NULL,
	[VALUE_VAT] [numeric](18, 3) NULL,
	[TOTAL_AMOUNT_INCLUDE_VAT] [numeric](18, 3) NULL,
	[LEST_DEPOSIT] [numeric](18, 3) NULL,
	[TOTAL_AMOUNT_DUE] [numeric](18, 3) NULL,
	[RECEIVE_NOTE] [nvarchar](150) NULL,
	[STATUS_PAY] [bit] NULL,
	[PAY_NOTE] [nvarchar](150) NULL,
 CONSTRAINT [PK_ITEM_RECIEVE_MASTER] PRIMARY KEY CLUSTERED 
(
	[RECEIVE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

